name: E2E Security and Code Quality Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-security-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: SonarQube Scan
      - name: SonarQube Scan
        id: sonarqube
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Step 2: Snyk Scan (always runs)
      - name: Snyk Security Scan
        id: snyk
        if: always()
        uses: snyk/actions@v4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      # Step 3: OWASP ZAP Scan (always runs)
      - name: OWASP ZAP Baseline Scan
        id: zap
        if: always()
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
        continue-on-error: true
